apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  ports:
    - port: 80
  selector:
    app: phpmyadmin
    tier: frontend
  type: LoadBalancer

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
      tier: frontend
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
        tier: frontend
    spec:
      containers:
      - image: phpmyadmin/phpmyadmin
        name: phpmyadmin
        env:
        - name: PMA_HOST
          valueFrom:
             configMapKeyRef:
               name: db-config-map
               key: DB_HOST
        - name: PMA_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
             configMapKeyRef:
               name: db-config-map
               key: DB_PASSWORD
        ports:
        - containerPort: 80
          name: phpmyadmin
        
