---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wpcli
  labels:
    app: wpcli
spec:
  selector:
    matchLabels:
      app: wpcli
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: wpcli
    spec:
      containers:
      - image: wordpress:cli
        name: wpcli
        volumeMounts:
        - name: wpcli-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wpcli-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
